### ISSUE TITLE
Refactor to remove parameters from mesh classes

### ISSUE THREAD

**Issue by samuelpowell** [toastpp/toastpp#7]
See #8

**Comment by mschweiger** [comment]
Removal of parameters (plist) from the Mesh class in branch no_mesh_prm.

**Comment by mschweiger** [comment]
Interface changes as result of parameter removal from Mesh class:

Parameter-related methods in Mesh have been removed:
Mesh::ParamAverage
Mesh::ResetCoeff_homog
Mesh::ResetCoeff_region
Mesh::ResetCoeff_sqrt

TFwdsolver::Project_cplx has been removed, because it was relying on the mesh-stored refractive index. This method was marked obsolete before. Replacement is TFwdSolver::Project_single.

The option to set initial parameter values from the mesh in some command line applications (fwdfem, supertoast) is no longer available.

Matlab interface: toastMesh/Mvec now must provide a refractive index (either global or nodal) as a command line parameter, since the fallback method of reading from mesh parameters no longer exists. (this was optional before).

**Comment by samuelpowell** [comment]
@mschweiger this is excellent. Could you create a pull request for your branch and we can discuss further there?
